server:
  port: 11002
spring:
  application:
    name: reader-springcloud-eureka02

eureka:
  instance:
    hostname: eureka02.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01.com:11001/eureka/,http://eureka03.com:11003/eureka/