server:
  port: 29999

spring:
  application:
    name: reader-springcloud-facade

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:11001/eureka/,http://eureka02.com:11002/eureka/,http://eureka03.com:11003/eureka/
  instance:
    instance-id: reader-springcloud-facade
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
