spring:
  application:
    name: reader-springcloud-dao

mybatis:
  # config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qijianguo.reader.pojo
  mapper-locations:
  - classpath:mybatis/mapper/*.xml


